circify/circ

scripts/build_mpc_zokrates_test.zsh, scripts/zokrates_test.zsh
Tested output on both machines!
=> Updated time cmd for both OSX and LINUX

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, src/target/milp/mod.rs, src/target/mod.rs
=> CBC dependency for LPs

examples/ZoKrates/mpc/const_tests/2pc_const_arith.zok, examples/ZoKrates/mpc/const_tests/2pc_const_bool.zok, scripts/build_mpc_zokrates_test.zsh, scripts/test_aby.py, src/target/aby/trans.rs
Note* currently convert string value of constant bitvector from `#b...` to `0b...`
=> added const value translation for ABY

examples/ZoKrates/mpc/array_tests/2pc_array_ret.zok, examples/ZoKrates/mpc/array_tests/2pc_array_sum.zok, examples/ZoKrates/mpc/function_tests/2pc_function_sum.zok, examples/circ.rs, scripts/build_mpc_zokrates_test.zsh, scripts/test_aby.py, src/target/aby/assignment/mod.rs, src/target/aby/mod.rs, src/target/aby/output.rs, src/target/aby/trans.rs, third_party/ABY_templates/cpp_template.txt
- Added array tests
- Added function call tests
=> Added support for multiple outputs in test cases

driver.py
=> add flamegraph action

driver.py, src/ir/term/ty.rs
Credits to @kwantam for noticing the bug. Thank you!
=> Bugfix: non-recursive type-checking for Op::Map

src/ir/term/mod.rs, src/ir/term/ty.rs
A pretty minimal addition, but I'll figure we'll let Jess/Lef add what they need.
=> function calls

examples/C/r1cs/add.c
=> add.c: mpc_main -> main

Cargo.lock, Cargo.toml, src/front/datalog/mod.rs, src/front/datalog/parser.rs, src/front/zsharp/zvisit/eqtype.rs, src/front/zsharp/zvisit/zconstlitrw.rs, src/front/zsharp/zvisit/zstmtwalker/mod.rs, src/front/zsharp/zvisit/zstmtwalker/zexprtyper.rs, third_party/ZoKrates/zokrates_pest_ast/Cargo.toml, third_party/ZoKrates/zokrates_pest_ast/src/lib.rs
pest::prec_climber has been deprecated.
=> Update pest parsers to use PrattParser

Cargo.lock, Cargo.toml, circ_fields/Cargo.lock, circ_fields/Cargo.toml, circ_fields/src/int_field.rs, circ_fields/src/lib.rs
@emlaufer @alex-ozdemir I think this fixes some recent issues with builds. Let's see what CI thinks of my thinking.
=> bump deps to avoid yanked packages ; fix some clippy lints in circ_fields

src/ir/opt/cfold.rs, src/ir/term/lin.rs, src/ir/term/mod.rs, src/ir/term/precomp.rs, src/ir/term/serde_mods.rs, src/target/r1cs/mod.rs
Also, for data-structures thereof.
Crediting Colin, b/c this is based on his PR.
Co-Authored-By: Collin Zhang <collinzrj@gmail.com>
=> Slightly better serde implementation for Term

examples/circ.rs, examples/zxc.rs, src/target/r1cs/mod.rs, src/target/r1cs/trans.rs
Co-authored-by: Riad S. Wahby <rsw@jfet.org>
=> Avoid R1CS copy

src/target/r1cs/trans.rs
Before, whenever we constructed a bit-wise encoding of a BV, we also debitified it into a UINT encoding.
Now, we do the debitification on-demand. This saves ~10-15% of compilation time.
While debitification is free from the perspective of R1CS, it is costly for compilation time.
I measured compile time for the sha2 round function.
```terminal
Benchmark #1: ./circ-old third_party/ZoKrates/zokrates_stdlib/stdlib/hashes/sha256/shaRound.zok r1cs
Time (mean ± σ):      1.219 s ±  0.019 s    [User: 1.145 s, System: 0.071 s]
Range (min … max):    1.180 s …  1.240 s    10 runs
Benchmark #2: ./circ-new third_party/ZoKrates/zokrates_stdlib/stdlib/hashes/sha256/shaRound.zok r1cs
Time (mean ± σ):      1.055 s ±  0.024 s    [User: 987.1 ms, System: 65.9 ms]
Range (min … max):    1.026 s …  1.094 s …
```
=> lazy debitification in r1cs::trans

circ_opt/README.md, circ_opt/src/lib.rs, driver.py, examples/C/smt/assert_assume_fails.c, examples/C/smt/assert_assume_ok.c, examples/C/smt/assert_fails.c, examples/C/smt/defined_return.c, examples/C/smt/shl_fails_1.c, examples/C/smt/shl_fails_2.c, examples/C/smt/shl_fails_3.c, examples/C/smt/shl_fails_4.c, examples/C/smt/shl_ok.c, examples/circ.rs, scripts/test_c_smt.zsh, src/front/c/ast_utils.rs, src/front/c/mod.rs, src/front/c/term.rs, src/front/c/types.rs, src/ir/opt/cfold.rs
- Added COpt to Circ options
- Cherrypicked https://github.com/circify/circ/pull/100 
- renaming C primitive terms (e.g. CInt --> Int) 
- Added AND case in cfold pass
=> Introducing SV Comp-style tests for C Frontend

src/ir/term/mod.rs
All credits to Evan for finding this.
=> Access array without it cloning it.

Cargo.lock, circ_opt/README.md, circ_opt/src/lib.rs, src/front/c/mod.rs, src/front/datalog/mod.rs, src/front/zsharp/mod.rs, src/front/zsharp/zvisit/zstmtwalker/mod.rs, src/front/zsharp/zvisit/zstmtwalker/zexprtyper.rs, src/ir/opt/cfold.rs, src/ir/opt/mod.rs, src/ir/term/dist.rs, src/ir/term/text/mod.rs, src/ir/term/ty.rs
Flag: `--ir-frequent-gc true`
Reduces memory usage on Jess & Eli's pgm from 398MB to 285MB.
=> GC after each optimization

src/target/r1cs/opt.rs
The R1CS optimizer tracks variable uses so that it can run faster.
Our tracker would sometimes think that a variable has cancelled from a constraint when it had not.
Now, the tracker is conservative, but correct.
=> r1cs optimization bugfix: use tracking

examples/ZoKrates/pf/mem/ann_transcript_const.zok, examples/ZoKrates/pf/mem/arr_of_str.zok, examples/ZoKrates/pf/mem/two_level_ptr.zok, examples/ZoKrates/pf/mem/volatile.zok, examples/ZoKrates/pf/mem/volatile_struct.zok, examples/circ.rs, scripts/ram_test.zsh, src/front/zsharp/mod.rs, src/front/zsharp/term.rs, src/front/zsharp/zvisit/walkfns.rs, src/front/zsharp/zvisit/zvmut.rs, src/ir/opt/mem/ram/volatile.rs, src/ir/opt/mod.rs, src/ir/proof.rs, src/ir/term/mod.rs, src/ir/term/text/mod.rs, third_party/ZoKrates/zokrates_parser/src/zokrates.pest, third_party/ZoKrates/zokrates_pest_ast/src/lib.rs
when the `transcript` type qualifier is used.
=> User-directed transcript-based RAM checking.

driver.py, scripts/spartan_zok_test.zsh, scripts/zokrates_test.zsh, src/target/r1cs/mod.rs, src/target/r1cs/spartan.rs
Spartan bit-rotted because CI was misconfigured.
=> Fix spartan (and include its tests in CI)

circ_hc/src/rc/example_u8.rs, circ_hc/src/rc/macro_.rs, circ_hc/src/rc/template.rs, examples/ZoKrates/pf/2024_05_24_benny_bug.zok, examples/ZoKrates/pf/2024_05_24_benny_bug_tr.zok, scripts/zokrates_test.zsh, src/circify/mod.rs, src/front/datalog/parser.rs, src/ir/opt/mem/lin.rs, src/ir/opt/mem/ram/volatile.rs, src/ir/opt/visit.rs, src/ir/term/dist.rs
It was just unhandled which is bad :(
=> handle CStore in linearization pass
