- .gitignore
- scripts/zx_tests/casts_to_field.zx
- scripts/zx_tests/casts_to_u16.zx
- scripts/zx_tests/casts_to_u32.zx
- scripts/zx_tests/casts_to_u64.zx
- src/front/zsharp/mod.rs
- src/front/zsharp/term.rs
- src/front/zsharp/zvisit/zgenericinf.rs
- src/front/zsharp/zvisit/zstmtwalker/mod.rs
- src/ir/opt/cfold.rs
- src/ir/term/bv.rs
- src/ir/term/mod.rs
- src/target/r1cs/trans.rs
- third_party/ZoKrates/zokrates_stdlib/stdlib/EMBED.zok
- third_party/ZoKrates/zokrates_stdlib/stdlib/utils/casts/u16_from_bits.zok
- third_party/ZoKrates/zokrates_stdlib/stdlib/utils/casts/u16_to_field.zok
- third_party/ZoKrates/zokrates_stdlib/stdlib/utils/casts/u16_to_u32.zok
- third_party/ZoKrates/zokrates_stdlib/stdlib/utils/casts/u16_to_u64.zok
- third_party/ZoKrates/zokrates_stdlib/stdlib/utils/casts/u32_from_bits.zok
- third_party/ZoKrates/zokrates_stdlib/stdlib/utils/casts/u32_to_field.zok
- third_party/ZoKrates/zokrates_stdlib/stdlib/utils/casts/u32_to_u64.zok
- third_party/ZoKrates/zokrates_stdlib/stdlib/utils/casts/u64_from_bits.zok
- third_party/ZoKrates/zokrates_stdlib/stdlib/utils/casts/u64_to_field.zok
- third_party/ZoKrates/zokrates_stdlib/stdlib/utils/casts/u8_from_bits.zok
- third_party/ZoKrates/zokrates_stdlib/stdlib/utils/casts/u8_to_bits.zok
- third_party/ZoKrates/zokrates_stdlib/stdlib/utils/casts/u8_to_field.zok
- third_party/ZoKrates/zokrates_stdlib/stdlib/utils/casts/u8_to_u16.zok
- third_party/ZoKrates/zokrates_stdlib/stdlib/utils/casts/u8_to_u32.zok
- third_party/ZoKrates/zokrates_stdlib/stdlib/utils/casts/u8_to_u64.zok
This PR does two things:
- Fixes some scoping issues in Z# having to do with the context in which function and struct definitions are interpreted.
- Improves speed and reduces TermTable memory consumption by 2x (by keying on Arc<TermData> rather than TermData)
- Improves speed for Z# array handling with a BTreeMap -> HashMap swap
- Adds intrinsic widening casts in Z#. These were previously handled by bit-splitting, which is wasteful.
On array-heavy Z# programs, this PR improves speed by about 5x and memory consumption by roughly the same.
(EDIT: mentioned one other thing this PR does)
> zsharp fixes ; speed improvements

- examples/C/mpc/benchmarks/2pc_biomatch_40x.c
- src/ir/term/ty.rs
In *non-recursive* type-checking, perhaps better called *type computing*
we perform a minimal traversal in order to compute the type of a term,
without recursively type-checking it. Informally, we assume it is well
typed, and do the minimal amount of work needed to compute its type.
Two improvements:
1. No longer implemented with recursion.
2. Caches all intermediate results.
Implementation:
* `check_dependencies(Term) -> Vec<Term>`: maps a terms to the immediate
children of it whose types are needed to compute its type.
* `check_raw_step(Term, TypeTable) -> Sort`: assumes those children have
their types in the table, and computes this term's type.
* `check_raw`: glues the two above functions together into a suitable
traversal. Similar to `rec_check_raw`, but the traversal isn't total. …
> Improve non-recursive type-checking

- Cargo.toml
- src/ir/opt/tuple.rs
Change: The tuple elimination pass now represents its *tuple trees*
using nested persistent vectors of non-tuple terms, rather than standard
terms.
Rationale: When large oblivious arrays are transformed to tuples, said
tuples are large, and updates to them use the tuple update operator.
However, when we eliminate those tuples, we essentially replace the
update operator with an explicit tuple (tree). For a large number of
updates, this entails quadratic memory usage.
Of course, it doesn't *need* to: each update only modifies one spot in
the tuple.
Thus, in this patch, we change the representation of tuples in tuple
tree from a standard term---whose children are in a vector---such that
the children are now in a persistent vector from the `im` crate. This
allows for an "update" operation on …
> Eliminate tuples with persistent vectors

- Cargo.lock
- Cargo.toml
- examples/zxc.rs
- scripts/zx_tests/typedef_1.zx
- scripts/zx_tests/typedef_2.zx
- scripts/zx_tests/typedef_3.zx
- scripts/zx_tests/typedef_4.zx
- scripts/zx_tests/typedef_5.zxf
- src/circify/mod.rs
- src/front/zsharp/TODO
- src/front/zsharp/mod.rs
- src/front/zsharp/parser.rs
- src/front/zsharp/term.rs
- src/front/zsharp/zvisit/eqtype.rs
- src/front/zsharp/zvisit/walkfns.rs
- src/front/zsharp/zvisit/zgenericinf.rs
- src/front/zsharp/zvisit/zstmtwalker/mod.rs
- src/front/zsharp/zvisit/zstmtwalker/zexprtyper.rs
- src/front/zsharp/zvisit/zvmut.rs
- src/ir/opt/cfold.rs
- src/ir/term/mod.rs
- src/target/aby/trans.rs
- src/target/ilp/trans.rs
- src/target/r1cs/trans.rs
- third_party/ZoKrates/zokrates_parser/src/zokrates.pest
- third_party/ZoKrates/zokrates_pest_ast/src/lib.rs
This PR breaks cycles between the term cache and the constant folding machinery. It also adds a couple Drop implementations that explicitly call the garbage collector (the C front-end might want one, too---not sure!)
For Z#, this adds
- a unary operator `#` that strictly evaluates (i.e., constant folds) its argument. As a special case, an assignment's RHS is treated strictly if its LHS is `#( ... )`
- the `condition ? consequent : alternative` flavor of ternary operator - exactly the same as `if foo then bar else baz fi`
- typedefs: `type Foo = field[7]` or whatever.
Typedefs have one limitation: if a typedef `Bar` refers to a struct `Foo` in module A, then to use `Bar` in module B one must also import `Foo`.
@alex-ozdemir: before we land this PR, we should land …
> improve memory consumption ; add Z# strict unary op, ternary ?:, and type aliases

- src/ir/opt/cfold.rs
- src/ir/opt/mod.rs
- src/ir/term/mod.rs
- src/ir/term/ty.rs
@alex-ozdemir reminded me that tests run concurrently, meaning we actually have to worry about deadlocking etc in the garbage collector. Mea culpa.
This PR makes the collector hold one lock (on TERMS, TYPES, or FOLDS) at a time.
It also adds a new lock, COLLECT, only in `#[cfg(test)]`. The collector takes this read-write; constant-folding and type-checking take it read-only. This means that garbage collection can't run while folding or typing is going on, which otherwise could potentially result in terms being collected while they're still needed.
> concurrency fixes for garbage collection

- src/ir/opt/sha.rs
- src/ir/term/precomp.rs
- src/ir/term/text/mod.rs
It detects bitwise BV ITEs expressed using and XOR/OR of ANDs with a
NOT. Now it triggers more often.
This cuts a few percentage points (~10%) worth of constraints on ZoK's
shaRound circuit.
> Broader SHA bitwise ITE optimization

- examples/ZoKrates/pf/mm4_cond.zok
- scripts/zokrates_test.zsh
- src/front/zsharp/mod.rs
- src/ir/opt/cfold.rs
- src/ir/opt/mem/lin.rs
We received a benchmark from Lef which essentially checked the following:
(cond ? A*B : A*C)[i] == v
where A, B, C are 4 by 4 matrices, cond is a bool, i is an index, and v a value.
The expected number of constraints is n^3: order 64 , but compile time and constraint count were in the thousands.
I investigated finding a number of things:
* the Z# front-end entered a conditional branch for the ternary, causing the MM to happen in a conditional context
* while the MM has an oblivious access pattern, since `i` is variable, the oblivious pass wasn't really helping
* there were some weird non-constant indices floating around like (ite cond 0 0)
The three optimizations fix these problems:
* If the Z# frontend isn't in assertion isolation mode, don't enter a conditional branch for an ITE
* …
> Improve conditional matrix mult with 3 opts

- examples/ZoKrates/pf/mm3.zok
- examples/ZoKrates/pf/mm4.zok
- examples/ZoKrates/pf/mm5.zok
- src/ir/opt/mem/lin.rs
- src/ir/opt/mem/ram.rs
- src/ir/term/mod.rs
- src/ir/term/precomp.rs
- src/ir/term/text/mod.rs
- src/target/r1cs/mod.rs
The previous implementation for all 3 structures would separately serialize each term in a precomputation. This was very bad, because precomputations can be quite large, and the different terms typically share large numbers of sub-terms. This can be quadratic blowup.
Change list:
* add input/output type metadata to PreComp (this makes the type of variables in a PreComp clear)
* add textual serialization and parsing for PreComp (and include this in Computation)
* add serde implementations for Computation and PreCop based on the text formats.
* modify the R1cs serde derive so that the `Vec<Term>` is tuplized before serde
This reduces our prover-key size for `verifyEddsa.zok` from wildly large (>450GB) to 171MB.
Collin and Anna first observed this bug. Collin's PR #118 works around it (among …
> Better serde for Computation, PreComp, R1cs

- Cargo.lock
- Cargo.toml
- src/target/r1cs/bellman.rs
Bellman keys (pk and vk) expose non-trait read and write functions for interacting with `io::{Read,Write}`. They don't expose serde impls. We need to serde them.
Previously, we used the io interface to convert from/to a `Vec<u8>`, whose serde impl we used.
This was a bad idea b/c the serde impl for `Vec<u8>` is bad. It gets stuck with the generic serde impl for `Vec`, rather than using `(de)serialize_bytes`.
Now, we have serde-impl'd wrapper types for pk and vk that do the right thing.
By my measurements, this decreases the cost of serializing a circ pk by about 84%.
> Better serde impl for bellman keys

- src/target/r1cs/mod.rs
- src/target/r1cs/trans.rs
Fixes 4 bugs in R1CS lowering:
* division-by-zero in finite fields: previously, this always caused incompleteness. Now, the behavior depends on the CIRC_RELAXATION envvar:
* CIRC_RELAXATION=incomplete: divide-by-0 causes incompletenes
* CIRC_RELAXATION=nondet: divide-by-0 allows the output to take any value
* CIRC_RELAXATION=det: divide-by-0 forces the output to 0
* bit-vector overshift: previously, this cause incompleteness. Now, we follow the semantics of SMT-LIB (the result saturates).
* bit-vector udiv-by-zero: previously, the output value was an unconstrained bit-vector. Now, it is MAX (following SMT-LIB).
* bit-vector comparisons: previously, the prover could lie, claiming that x < y when actually x >= y. All bit-vector comparisons are affected, including those in udiv and urem.
* …
> Bugfixes: R1CS lowering (includes a soundness bugfix)

- TODO.md
- driver.py
- examples/circ.rs
- src/ir/opt/mem/lin.rs
- src/ir/opt/mem/ram.rs
- src/ir/opt/mod.rs
- src/ir/opt/scalarize_vars.rs
- src/ir/term/extras.rs
- src/ir/term/fmt.rs
- src/ir/term/mod.rs
- src/ir/term/text/mod.rs
- src/target/aby/trans.rs
- src/target/r1cs/trans.rs
In the new approach, all variable metadata is stored per-variable.
This makes it easier to add new kinds of metadata, and to serialize that metadata.
> change metadata serialization & representation

- Cargo.lock
- circ_fields/Cargo.lock
- circ_fields/Cargo.toml
- circ_fields/src/ff_field.rs
- circ_fields/src/int_field.rs
- circ_fields/src/lib.rs
- circ_fields/src/size.rs
- circ_fields/src/test.rs
Reduces R1CS lowering memory usage by ~40% on a persistent memory benchmark.
> Inline small elements in `FieldV`.

- src/ir/opt/mem/lin.rs
The linear scan converts `store` operation on `arrays` into `ITE` over an updated tuple for every index. e.g `(store A I V)` -> `(ite (= I 0) ((update 0) T V) (ite (= I 1) ((update 1) T V) T)))` where `T` is the tuple that represents `A`.
Later, the tuple pass converts translate an ITE over a tuple of length `n` into `n` different non-tuple ITEs, causing a quadratic increase in term.
This fix will cause the linear scan to covert `store` into `field` operation over a `tuple` that prevents the later quadratic blow-up.
> convert array::store -> tuple::field

- src/ir/opt/mem/ram/checker.rs
- src/target/r1cs/trans.rs
We called the wrong function...
This is a soundness bug.
Credit to Anna for reporting this.
> Fix bug in r1cs lowering for bv cmps

- examples/ZoKrates/pf/maj.zok
- examples/ZoKrates/pf/maj.zok.pin
- examples/ZoKrates/pf/sha_rot.zok
- examples/ZoKrates/pf/sha_rot.zok.pin
- examples/ZoKrates/pf/sha_temp1.zok
- examples/ZoKrates/pf/sha_temp1.zok.pin
- examples/ZoKrates/pf/sha_temp2.zok
- examples/ZoKrates/pf/sha_temp2.zok.pin
- examples/ZoKrates/pf/test_sha256.zok
- examples/ZoKrates/pf/test_sha256.zok.pin
- scripts/zokrates_test.zsh
- src/front/zsharp/mod.rs
- src/target/r1cs/mod.rs
- src/target/r1cs/trans.rs
- src/target/r1cs/wit_comp.rs
for m = majority(a,b,c),
we were lowering
(-ab + bc + ac - 2abc)
instead of
(ab + bc + ac - 2abc)
Whoops! This is a functional correctness bug: we were lowering soundly and completely, for the wrong specification.
Credit to Anna for raising the issue!
> r1cs: fix boolean majority

- Cargo.lock
- circ_hc/Cargo.toml
- circ_hc/src/rc/example_u8.rs
- circ_hc/src/rc/macro_.rs
- circ_hc/src/rc/template.rs
- circ_hc/src/test/bench.rs
- circ_hc/src/test/mod.rs
- circ_hc/src/test/tiny.rs
Previously, a GC call would scan the HC table, identifying dead nodes.
Now, whenever a `Node` is destroyed, if it's ready to be GC'd, it gets added to a list. That list is used at GC time instead of the scan.
This substantially decreases the cost of running GC many times (as the Z# FE does).
> Optimize GC

- src/ir/opt/mem/obliv.rs
- src/ir/opt/mem/ram/volatile.rs
- src/ir/opt/mod.rs
- src/ir/term/extras.rs
* Improve the oblivious RAM pass by killing the hack where we treat selects as arrays.
* Fix a bug where the volatile RAM pass would not place selects before stores against the same array
* Improve that volatile RAM pass by placing selects against the same array literal in *the same RAM*. Before, they would each end up in different RAMs, which sucks. This is especially bad for ROMs.
> Improve RAM: oblivious & volatile

- src/target/r1cs/proof.rs
- src/target/r1cs/spartan.rs
Both the bellman and spartan backends were using unbuffered IO. Ouch.
> optimize prover: buffered IO

- src/target/r1cs/mod.rs
- src/target/r1cs/opt.rs
Previously, we would eliminate only final-round witnesses. This is obviously sound, but sub-optimal.
Anna has found some protocols (SHA with lookups) where the sub-optimality matters, so I've made the optimizer a bit more aggressive.
> Make the IR1CS optimizer more aggressive

- examples/ZoKrates/pf/2024_06_02_chad_bug.zok
- scripts/zokrates_test.zsh
- src/ir/opt/mem/obliv.rs
recognize scalar variables as tuple-free
> bugfix: opt::mem::obliv

- src/ir/opt/mem/ram/checker.rs
- src/ir/term/dist.rs
- src/ir/term/ext/poly.rs
- src/ir/term/ext/ram.rs
- src/ir/term/mod.rs
- src/target/smt/mod.rs
Decreases memory use in matrix multiply by up to 2.5x
> Arc<> in Sort

- examples/circ.rs
- src/ir/opt/mem/ram/checker.rs
- src/ir/opt/mem/ram/checker/rom.rs
- src/ir/opt/mem/ram/set.rs
It was spuriously three because of imprecise dependency tracking
> Reduce the number of rounds in ROM checking to 2.

- examples/ZoKrates/pf/const_linear_lookup.zok
- examples/circ.rs
- examples/opa_bench.rs
- scripts/zokrates_test.zsh
- src/circify/mod.rs
- src/ir/opt/chall.rs
- src/ir/opt/mem/lin.rs
- src/ir/opt/mod.rs
- src/ir/term/mod.rs
- src/lib.rs
- src/target/aby/trans.rs
- src/target/r1cs/opt.rs
- src/target/r1cs/wit_comp.rs
- src/target/smt/mod.rs
For memories with constant values that have sorts which are linear groups, there is a way to optimize linear-scan memory-checking.
This patch implements that optimization.
> Opt: memory: linear for [group] const values

- examples/circ.rs
- examples/datalog/parse_test/one_rule.pl
- examples/zxc.rs
- scripts/ram_test.zsh
- scripts/spartan_zok_test.zsh
- scripts/test_datalog.zsh
- scripts/zokrates_test.zsh
- src/front/zsharp/mod.rs
- src/front/zsharp/term.rs
- src/front/zsharp/zvisit/zstmtwalker/mod.rs
- src/front/zsharp/zvisit/zstmtwalker/zexprtyper.rs
- src/ir/opt/cfold.rs
- src/ir/term/extras.rs
- src/ir/term/mod.rs
- src/target/r1cs/mod.rs
- src/util/once.rs
- third_party/ZoKrates/zokrates_pest_ast/src/lib.rs
Previously, the traversal stack held (node, children queued) pairs.
When visiting a node without it's children queued, we would queue them
all. They take a lot of memory!
Now, the stack holds children iterators.
> reduce traversal memory usage through iterators

- Cargo.toml
- src/front/datalog/error.rs
- src/front/zsharp/term.rs
- src/front/zsharpcurly/term.rs
- src/ir/term/dist.rs
- src/target/aby/utils.rs
- src/target/ilp/trans.rs
- src/target/r1cs/trans.rs
- third_party/ZoKratesCurly/zokrates_pest_ast/src/lib.rs
the example requires this flag but the build system did not know that
credits to Victor Miller for finding the issue
> build: add r1cs flag to zxc example
